pipeline {
  agent any
  triggers {
    // poll repo every 1 minute for changes
    pollSCM('* * * * *')
  }  
  stages {
    stage("Clone repo...") {
      steps {
        git poll: true, 
	branch: env.BRANCH_NAME,
	url: 'https://github.com/carlosseco29/JenkinsTests.git'
      }
    }
    stage("Run Hello World script") {
      steps {
        sh "./myscript.sh"
      }
    }
    stage("Exit") {
      steps {
        echo "Exiting..."
      }
    }
  }
}
