pipeline {
  agent any
  triggers {
    // poll repo every 1 minute for changes
    pollSCM('* * * * *')
  }  
  stages {
    stage("Clone repo...") {
      steps {
        git poll: true, 
	branch: env.BRANCH_NAME,
	url: 'https://github.com/carlosseco29/JenkinsTests.git'
      }
    }
    stage("Run Hello World script master") {
      when {
        branch 'master'
      }
      steps {
        echo "master branch"
        sh "./myscript.sh"
      }
    }
    stage("Run Hello World script develop") {
      when {
        branch 'develop'
      }
      steps {
        echo "develop branch"
        sh "./myscript.sh"
      }
    }
    stage("Run Hello World script feature") {
      when {
        expression { BRANCH_NAME ==~ /(feature_.*)/ }
      }
      steps {
        echo "feature branch"
        sh "./myscript.sh"
      }
    }
    stage("Exit") {
      steps {
        echo "Exiting..."
      }
    }
  }
}
